pub struct WeightConfig {
    pub input_size: usize,
    pub hidden_size: usize,
    pub output_size: usize,
    pub input_gate_input_weights: Vec<f32>,
    pub input_gate_input_biases: Vec<f32>,
    pub input_gate_hidden_weights: Vec<f32>,
    pub input_gate_hidden_biases: Vec<f32>,
    pub forget_gate_input_weights: Vec<f32>,
    pub forget_gate_input_biases: Vec<f32>,
    pub forget_gate_hidden_weights: Vec<f32>,
    pub forget_gate_hidden_biases: Vec<f32>,
    pub cell_gate_input_weights: Vec<f32>,
    pub cell_gate_input_biases: Vec<f32>,
    pub cell_gate_hidden_weights: Vec<f32>,
    pub cell_gate_hidden_biases: Vec<f32>,
    pub output_gate_input_weights: Vec<f32>,
    pub output_gate_input_biases: Vec<f32>,
    pub output_gate_hidden_weights: Vec<f32>,
    pub output_gate_hidden_biases: Vec<f32>,
}